openapi: 3.0.3
info:
  title: Agenda API
  description: A simple API to allow server-client communications
  contact:
    name: Szabolcs Bazil Papp
    email: papp.szabolcs.bazil@gmail.com
  version: 1.0.0
tags:
  - name: Agenda
    description: To-Do list related operations
paths:
  /agenda:
    get:
      summary: List all items in the agenda.
      description: ...
      tags:
        - Agenda
      operationId: getAllTasks
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Create a new item in the agenda.
      description: ...
      tags:
        - Agenda
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /agenda/{id}:
    put:
      summary: Update a task in the agenda
      description: ...
      tags:
        - Agenda
      operationId: updateTask
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Unknown task

    delete:
      summary: Delete a task in the agenda
      description: ...
      tags:
        - Agenda
      operationId: deleteTask
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Ok
        '404':
          description: Unknown task

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: |
            Unique identifier of a given task.
          example: 1024
        title:
          type: string
          example: Wash the dishes
        description:
          type: string
          example: Washing the dishes is very important!
        completed:
          type: boolean
          default: false
        important:
          type: boolean
          default: false
      required: [ title, completed, important ]
